version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=pedregal_report
      - POSTGRES_USER=admin_pedregal
      - POSTGRES_PASSWORD=HNrMvA7sPjNULKmjEMvR
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=lineaetica@elpedregalsa.com
      - PGADMIN_DEFAULT_PASSWORD=Elpedregaletico
    ports:
      - 5050:80
